export const PUT_CLASSES_LIST = 'PUT_CLASSES_LIST';
export const PUT_CLASSROOMS_LIST = 'PUT_CLASSROOMS_LIST';
export const PUT_TEACHERS_LIST = 'PUT_TEACHERS_LIST';
export const PUT_HOURS_LIST = 'PUT_HOURS_LIST';