export const REQUESTED = 'FETCHING_TIMETABLE_OBJECT_REQUESTED';
export const SUCCEEDED = 'FETCHING_TIMETABLE_OBJECT_SUCCEEDED';
export const FAILED = 'FETCHING_TIMETABLE_OBJECT_FAILED';
export const NOT_FOUND = 'TIMETABLE_OBJECT_NOT_FOUND';
export const PUT_LAST_UPDATE_DATE = 'PUT_TIMETABLE_OBJECT_LAST_UPDATE';